---

- hosts: dokku
  roles:
  - role: acl

  - role: yoshzz.dokku
    dokku_vhost: dokku.mrgall.com
    dokku_version: 0.9.4
    dokku_plugins:
    - name: acl
      repo: https://github.com/dokku-community/dokku-acl.git
    - name: docker-options
      repo: https://github.com/dyson/dokku-docker-options.git
    - name: letsencrypt
      repo: https://github.com/dokku/dokku-letsencrypt.git
    - name: maintenance
      repo: https://github.com/dokku/dokku-maintenance.git
    - name: mariadb
      repo: https://github.com/dokku/dokku-mariadb.git

  - role: dokku_users
    remove_dokku_users: []
    add_dokku_users:
    - name: wk
      ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKfVXabLvtPE8LhoD1+CjZ0hQHLq24eYo3fqFxGfp9IWNN8pXUQH1VpiSs9qd+YQH2KeiJubXaLG61fm+hRLreNn8HLu1sQEgmeLjl2IREk/yrfEWiPuoboN90KHy187gK515yVQmx1HFqQ9112fpVhnbyU/4D2sx07kpUDIR97OC1NW+XQjlWF0+tRh1xU+EEALQbzSVBLobz0DNlUPzDg2vNLbIcYSGvfiYGyj5Opb/tnK3JNN8EzYxZInBcVE52oLOYM3jPkiVWUuTFp5zq12JCiGXrxiPA4KtB/QjD6CbVHBc+eDMTFqMD26CjAuaSg6O/nCY7CSapESxDuVfd wk@wk-laptop
    - name: gdg-autodeployer-bot
      ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDeKhCJlpM7GCjgDYLD8PQ66HmkQCU1zE7GgMBzXO1efK5nLanHk1ze2UXDuToqFsE+PcUjbyeVJRpNEMzHoBl3TGvDSP7D7KLsWLQr8O291JyrDwpvo5MvZOqDvnRs3SiXxxYOh93RL3+VRvZQR+0afBDyrWkW1zXR3aWbzevBl+roq96MapWidWfV5KdDehw1MC7DO4/PGybXNUSc7QPJfxUYO37l+324y5PoG1vNcFBcnpBkysTvbQPgmRLObFY5mLv6IF4Ss5ijn4aCfEhDWmmpDRAZpSEsurEMejKm3WOUbe4lygEhJ0XZ/CGcwlyaVOvlEHeIry+bXeGziEEudeOQxups1ogJ57gfmD+PXzroKu4rwmPmYijF536/GzeOv+U6ryH/7YSmJ7mLvc4hJhsWHexe0xq2o4BuSeXlCgyiAinSIiYnoU+BaCmi59JNgnYqKU8rnlCIkNVwHSIAu5pjdaA8mtJmLYFLDPAibTUZl+6Vzv1q7zXoKUjyCbmdj1jVPuwGyxCvVZRl7N+YiXjyrV9G2VDLzvjPQZVsuXTbjy3NFvD/NCeQu7gEd1Lmpy2yhh9kwHX8CJGIrJJMQ3yNDC4VAhLZI3LzobjzC1jiONINHyUtJ4lTIwsBMuE1l/KyMeT0ohp6v53Sv8HmoJ5o4B+UerpeSqonSl9ruQ== dokku app deployment key
    - name: mrgall
      ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDFFzDPvc8875TegWwPNzBv1ZS21sEs+7XVvweFO6kUqOmWoThdlQBr4nTHIYXFVVvJ9VWmtL9sWjpJtK30xLRdsoe91N/9FyAZWQsN6pmPGU2MvUbKnaWGoa6q3s3uc6x2Vg/X9RcOlrDCxhvXzBY4xLQZGL8qRaeqvAQwH9yrpLeTK663QwLEjjardUVkQYe7CzaEJY/zAmdzDXUT0j0UnGK9LPjVU+CKiIyewIL7Cz+HDfucURysQDGINW3flVGH73Mf2RJOKYRaPaHrI97zDZGWPJptwGViQQikryZmJ58mhUhu2rYsuElIs0WVczJb8hCrfq3kcp7ps+JeVxRNKF0gqI3aqJ4mwM87KAB3Fiqr0Ho4LM3iIfm51/pL6XqknZSqKSzLxOXOV+G4pNQJ3QSXs8VcYSc/AYN6lR+cZtvTYt4s36vamUsgrMZP5YaJpDGsrI4HQz96Zm64p1LwAG7hU2nuVxMnun0z33SuySMVJZ8H6qK5q+wwMuI2qALs/rf+QDzIq0F0XiBYVK/9EAP38tNmE87zy6GCasOG3xhwfefLJxqI9jv9WeWyLCCIh9JKmb9NVBN3+Gqt9rzBR7c8dkKZAnORg6zsIv1VlDSXBWQBAlWeFj85nLx1nkVvKSd3oXiL1dNdDG/fg32q7KZMsVCO9d8GPZOPdBoWbQ== mrgall@home.mrgall.com

  - role: dokku_apps
    apps:
    - name: gdg.org.ua
      remove_acl_users: []
      acl_users: &gdg_acl_deployers
      - gdg-autodeployer-bot
      - wk
      domains:
      - gdg.org.ua
      - www.gdg.org.ua
      mariadb: true
      ssl: true
      email: &letsencrypt_email mrgall@mrgall.com
    - name: dev.gdg.org.ua
      remove_acl_users: []
      acl_users: *gdg_acl_deployers
      domains:
      - dev.gdg.org.ua
      - www.dev.gdg.org.ua
      mariadb: true
      ssl: true
      email: *letsencrypt_email

# vim: ft=ansible:
