---

- hosts: dokku
  vars_files:
  - vars/dokku-platform.yml
  - vars/dokku-users.yml
  - vars/dokku-apps.yml
  - vars/rclone-backup.yml

  tasks:

  - import_role:
      name: acl

  - import_role:
      name: security

  - import_role:
      name: yoshzz.dokku

  - import_role:
      name: dokku_users

  - import_role:
      name: dokku_apps

  - import_role:
      name: ansible-role-rclone
    become: yes
    become_method: sudo

# vim: ft=ansible:
