---

- hosts: dokku
  roles:
  - role: acl

  - role: yoshzz.dokku
    dokku_vhost: linode.mrgall.com
    dokku_version: 0.9.4
    dokku_plugins:
    - name: docker-options
      repo: https://github.com/dyson/dokku-docker-options.git
    - name: acl
      repo: https://github.com/dokku-community/dokku-acl.git

  - role: sshkeys
    sshkeys:
    - name: wk
      value: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKfVXabLvtPE8LhoD1+CjZ0hQHLq24eYo3fqFxGfp9IWNN8pXUQH1VpiSs9qd+YQH2KeiJubXaLG61fm+hRLreNn8HLu1sQEgmeLjl2IREk/yrfEWiPuoboN90KHy187gK515yVQmx1HFqQ9112fpVhnbyU/4D2sx07kpUDIR97OC1NW+XQjlWF0+tRh1xU+EEALQbzSVBLobz0DNlUPzDg2vNLbIcYSGvfiYGyj5Opb/tnK3JNN8EzYxZInBcVE52oLOYM3jPkiVWUuTFp5zq12JCiGXrxiPA4KtB/QjD6CbVHBc+eDMTFqMD26CjAuaSg6O/nCY7CSapESxDuVfd wk@wk-laptop
    - name: mrgall
      value: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDFFzDPvc8875TegWwPNzBv1ZS21sEs+7XVvweFO6kUqOmWoThdlQBr4nTHIYXFVVvJ9VWmtL9sWjpJtK30xLRdsoe91N/9FyAZWQsN6pmPGU2MvUbKnaWGoa6q3s3uc6x2Vg/X9RcOlrDCxhvXzBY4xLQZGL8qRaeqvAQwH9yrpLeTK663QwLEjjardUVkQYe7CzaEJY/zAmdzDXUT0j0UnGK9LPjVU+CKiIyewIL7Cz+HDfucURysQDGINW3flVGH73Mf2RJOKYRaPaHrI97zDZGWPJptwGViQQikryZmJ58mhUhu2rYsuElIs0WVczJb8hCrfq3kcp7ps+JeVxRNKF0gqI3aqJ4mwM87KAB3Fiqr0Ho4LM3iIfm51/pL6XqknZSqKSzLxOXOV+G4pNQJ3QSXs8VcYSc/AYN6lR+cZtvTYt4s36vamUsgrMZP5YaJpDGsrI4HQz96Zm64p1LwAG7hU2nuVxMnun0z33SuySMVJZ8H6qK5q+wwMuI2qALs/rf+QDzIq0F0XiBYVK/9EAP38tNmE87zy6GCasOG3xhwfefLJxqI9jv9WeWyLCCIh9JKmb9NVBN3+Gqt9rzBR7c8dkKZAnORg6zsIv1VlDSXBWQBAlWeFj85nLx1nkVvKSd3oXiL1dNdDG/fg32q7KZMsVCO9d8GPZOPdBoWbQ== mrgall@home.mrgall.com

  - role: thefinn93.letsencrypt
    letsencrypt_webroot_path: /var/www/html
    letsencrypt_email: mrgall@mrgall.com
    letsencrypt_cert_domains:
    - www.gdg.org.ua
    - gdg.org.ua
    - www.dev.gdg.org.ua
    - dev.gdg.org.ua
    letsencrypt_renewal_command_args: 
    - --renew-hook "systemctl restart nginx"
