---

- name: "Install dokku"
  shell: "wget -qO- https://raw.github.com/progrium/dokku/v{{ dokku_version }}/bootstrap.sh | DOKKU_TAG=v{{ dokku_version }} bash"
  args:
    creates: /var/lib/dokku
  become: yes
  become_method: sudo

- name: "Configure dokku vhost"
  copy: dest=/home/dokku/VHOST content={{ dokku_vhost }}
  become: yes
  become_user: dokku
  become_method: sudo

- name: Install plugins
  become: yes
  shell: dokku plugin:install "{{ item.repo }}" "{{ item.name }}"
  register: pluginadd_cmd
  changed_when: pluginadd_cmd.rc == 0 or (pluginadd_cmd.rc != 0 and 'already exists and is not an empty directory.' not in pluginadd_cmd.stderr)
  failed_when: pluginadd_cmd.rc != 0 and 'already exists and is not an empty directory.' not in pluginadd_cmd.stderr
  with_items: "{{ dokku_plugins }}"
